<?php

class ItemInventorySeeder extends Seeder {

    public function run() {

      $items = [
            array('p_code'          => 'ALAXAN FR CAP',
                  'name'            => 'ALAXAN FR CAP',
                  'desc'            => 'Alaxan FR',
                  'size'            => '50',
                  'lotNo'           => '1234567890',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '7.2',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'          => 'ALAXAN FR CAP',
                  'name'            => 'ALAXAN FR CAP',
                  'desc'            => 'Alaxan FR',
                  'size'            => '50',
                  'lotNo'           => '1234567891',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2019')),
                  'category'        => 'med',
                  'price_retail'    => '7.2',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'ALLERKID DROP',
                  'name'            => 'ALLERKID DROP',
                  'desc'            => 'Allerkid drop',
                  'size'            => '25',
                  'lotNo'           => '123456789xa',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '149.11',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'ALLERTA TAB',
                  'name'            => 'ALLERTA TAB',
                  'desc'            => 'Allerta tab',
                  'size'            => '50',
                  'lotNo'           => '1234567890g',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '20.55',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'APPEBON W/IRON CAP',
                  'name'            => 'APPEBON W/IRON CAP',
                  'desc'            => 'Appebon',
                  'size'            => '20',
                  'lotNo'           => '123456789hd0',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '17.62',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'ASPILETS TAB',
                  'name'            => 'ASPILETS TAB',
                  'desc'            => 'Aspilets tab',
                  'size'            => '40',
                  'lotNo'           => '1234567890nfgn',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2015')),
                  'category'        => 'med',
                  'price_retail'    => '2.5',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'ASPILETS TAB',
                  'name'            => 'ASPILETS TAB',
                  'desc'            => 'Aspilets tab',
                  'size'            => '40',
                  'lotNo'      => '1234asd890nfgn',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2030')),
                  'category'        => 'med',
                  'price_retail'    => '2.5',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'BIOFLU TAB',
                  'name'            => 'BIOFLU TAB',
                  'desc'            => 'Bioflu tab',
                  'size'            => '25',
                  'lotNo'           => '1234567kg890',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '6.18',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'CALCIBLOC 10MG CAP',
                  'name'            => 'CALCIBLOC 10MG CAP',
                  'desc'            => 'Calcibolic',
                  'size'            => '50',
                  'lotNo'           => '12345678yte90',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '51.76',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'BIOGESIC DROPS',
                  'name'            => 'BIOGESIC DROPS',
                  'desc'            => 'Biogesic',
                  'size'            => '50',
                  'lotNo'           => '12345678iu90',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '23.44',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            ),
            array('p_code'            => 'CALCIBLOC 5MG CAP',
                  'name'            => 'CALCIBLOC 5MG CAP',
                  'desc'            => 'Calcibolic',
                  'size'            => '50',
                  'lotNo'           => '1234567890fdf',
                  'expiry'          => date('Y-m-d', strtotime('01/30/2020')),
                  'category'        => 'med',
                  'price_retail'    => '16.42',
                  'price_package'   => '0',
                  'created_at'      => date('Y-m-d H:i:s'),
                  'updated_at'      => date('Y-m-d H:i:s'),
            )
      ];

      $inv = [
            array('p_code'     => 'ALAXAN FR CAP',
                  'lotNo'      => '1234567890',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 407,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'ALAXAN FR CAP',
                  'lotNo'      => '1234567891',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2019')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 2,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'ALLERKID DROP',
                  'lotNo'      => '123456789xa',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 3,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'ALLERTA TAB',
                  'lotNo'      => '1234567890g',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 30,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'APPEBON W/IRON CAP',
                  'lotNo'      => '123456789hd0',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 90,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'ASPILETS TAB',
                  'lotNo'      => '1234567890nfgn',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2015')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 124,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'ASPILETS TAB',
                  'lotNo'      => '1234asd890nfgn',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2030')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 124,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'BIOFLU TAB',
                  'lotNo'      => '1234567kg890',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 114,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'CALCIBLOC 10MG CAP',
                  'lotNo'      => '12345678yte90',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 11,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'BIOGESIC DROPS',
                  'lotNo'      => '12345678iu90',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 12,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            ),
            array('p_code'     => 'CALCIBLOC 5MG CAP',
                  'lotNo'      => '1234567890fdf',
                  'expiry'     => date('Y-m-d', strtotime('01/30/2020')),
                  'branchID'   => 1,
                  'packages'   => 0,
                  'retail'     => 54,
                  'created_at' => date('Y-m-d H:i:s'),
                  'updated_at' => date('Y-m-d H:i:s'),
            )
      ];

      DB::table('items')->insert($items);
      DB::table('inventory')->insert($inv);

      $this->command->info('Items and Inventory table seeded!');
    }
}